name: Task 4

on:
  push:
    branches:
      - main
    paths:
      - task4/**

env:
  NAME: task4

jobs:
  build:
    runs-on: [self-hosted, docker]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Decide Color
        shell: bash
        run: |
          if docker ps --format '{{.Names}}' | grep -q task4-blue
          then
            echo "COLOR=green" >> $GITHUB_ENV
            echo "OLD_COLOR=blue" >> $GITHUB_ENV
          else
            echo "COLOR=blue" >> $GITHUB_ENV
            echo "OLD_COLOR=green" >> $GITHUB_ENV
          fi
      - name: Build image
        run: docker build -t ${{ env.NAME }}-website:latest task4
      - name: Run new container Blue
        if: ${{ env.COLOR == 'blue' }}
        run: |
          docker run -d \
          --restart unless-stopped \
          -p 8080:80 \
          --name ${{ env.NAME }}-${{ env.COLOR }} \
          ${{ env.NAME }}-website:latest
      - name: Run new container Green
        if: ${{ env.COLOR == 'green' }}
        run: |
          docker run -d \
          --restart unless-stopped \
          -p 8081:80 \
          --name ${{ env.NAME }}-${{ env.COLOR }} \
          ${{ env.NAME }}-website:latest
      - name: Remove old container
        run: docker rm -f ${{ env.NAME }}-${{ env.OLD_COLOR }} || true