name: Task 3

on:
  push:
    tags:
      - v*

env:
  NAME: "task3-website"

jobs:
  build:
    runs-on: [self-hosted, docker]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: remove old container
        run: docker rm -f ${{ env.NAME }} || true
      - name: build image
        run: docker build -t ${{ env.NAME }}:${{ github.ref_name }} task3
      - name: Run new container
        run: |
          docker run -d \
          --restart unless-stopped \
          -p 8080:80 \
          --name ${{ env.NAME }} \
          ${{ env.NAME }}:${{ github.ref_name }}      
      - name: Print deployed version
        run: echo "Deployed version = ${{ github.ref_name }}"