name: Task 1

on:
  workflow_dispatch:
  
env:
  NAME: "task1-website"

jobs:
  build:
    runs-on: [self-hosted, docker]
    steps:
      - name: Code Checkout
        run: actions/checkout@v4
      - name: remove old container
        run: docker rm -f ${{ env.NAME }} || true
      - name: build image
        run: docker build -t ${{ env.NAME }}:1.0 task1
      - name: Run new container
        run: docker run -d -p 8080:80 --name ${{ env.NAME }} ${{ env.NAME }}:1.0